# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
    paths:
      - frontend/**
  pull_request:
    branches: [ "master" ]
    paths:
      - frontend/**
  workflow_dispatch:
  
jobs:
  build:       
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: frontend/LoanOut



    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.15
      uses: actions/setup-node@v3
      with:
        node-version: 18.15
        cache: 'npm'
    - run: |
        npm install -i
        npm run build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: equiplib
        path: frontend/LoanOut/www
